[package]
name = "meteo-handler"
version = "0.1.0"
edition = "2024"

[lib]
name = "meteo_handler"
crate-type = ["cdylib"]

[dependencies]
tarantool = "6.1.0"
serde = "1.0" 
serde_json = "1.0.89"
serde_with = "3.4"
fibreq = "0.1.10"